### ISSUE TITLE
Carnac crashes after some time

### ISSUE THREAD

**Issue by fredimachado** [Code52/carnac#272]
Hey everyone,

When I start Carnac it works fine for a while but then crashes silently.
I've had a look at error events and I found 2 right next to each other. It seems it's something related to Squirrel based on the first error (last one pasted here).

```
Log Name:      Application
Source:        Application Error
Date:          4/11/2020 5:24:25 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-QDRUOE4
Description:
Faulting application name: Carnac.exe, version: 2.3.13.0, time stamp: 0x5eee22a7
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1139, time stamp: 0xa8b891f5
Exception code: 0xe0434352
Fault offset: 0x0000000000043b29
Faulting process id: 0x1fdc
Faulting application start time: 0x01d6b26f0a0d3049
Faulting application path: C:\Users\Fredi\AppData\Local\carnac\app-2.3.13\Carnac.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: eb4af7a1-716b-488a-9860-696807bce7e1
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-04T06:24:25.146850400Z" />
    <EventRecordID>5035</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-QDRUOE4</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Carnac.exe</Data>
    <Data>2.3.13.0</Data>
    <Data>5eee22a7</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.18362.1139</Data>
    <Data>a8b891f5</Data>
    <Data>e0434352</Data>
    <Data>0000000000043b29</Data>
    <Data>1fdc</Data>
    <Data>01d6b26f0a0d3049</Data>
    <Data>C:\Users\Fredi\AppData\Local\carnac\app-2.3.13\Carnac.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>eb4af7a1-716b-488a-9860-696807bce7e1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

---------------------------------------------------------------------

Log Name:      Application
Source:        .NET Runtime
Date:          4/11/2020 5:24:24 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-QDRUOE4
Description:
Application: Carnac.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Squirrel.UpdateManager.Finalize()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-04T06:24:24.858832300Z" />
    <EventRecordID>5034</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-QDRUOE4</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Carnac.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Squirrel.UpdateManager.Finalize()

</Data>
  </EventData>
</Event>
```

**Comment by fredimachado** [comment]
And as expected, disabling auto update fixes the issue.

**Comment by mouse33333** [comment]
Many thanks, it works!
